# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  labels:
    k8s-app: kube-state-metrics
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    port: http-metrics
    scheme: http
    relabelings:
    - action: labeldrop
      regex: (pod|service|endpoint|namespace)
    scrapeTimeout: 30s
  - interval: 30s
    port: telemetry
    scheme: http
  jobLabel: k8s-app
  selector:
    matchLabels:
      app: kube-state-metrics
