# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: thanos-sidecar
  namespace: "monitoring"
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/version: v0.30.2
spec:
  groups:
  - name: thanos-sidecar
    rules:
    - alert: ThanosSidecarBucketOperationsFailed
      annotations:
        description: Thanos Sidecar {{ $labels.instance }} bucket operations are failing
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanossidecarbucketoperationsfailed
        summary: Thanos Sidecar bucket operations are failing
      expr: |
        sum by (job, instance) (rate(thanos_objstore_bucket_operation_failures_total{job=~".*thanos-sidecar.*"}[5m])) > 0
      for: 5m
      labels:
        severity: critical
    - alert: ThanosSidecarNoConnectionToStartedPrometheus
      annotations:
        description: Thanos Sidecar {{ $labels.instance }} is unhealthy.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanossidecarnoconnectiontostartedprometheus
        summary: Thanos Sidecar cannot access Prometheus, even though Prometheus seems healthy and has reloaded WAL.
      expr: |
        thanos_sidecar_prometheus_up{job=~".*thanos-sidecar.*"} == 0
        AND on (namespace, pod)
        prometheus_tsdb_data_replay_duration_seconds != 0
      for: 5m
      labels:
        severity: critical
