# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: registry.k8s.io/prometheus-adapter/prometheus-adapter
    newName: registry.sighup.io/fury/prometheus-adapter/prometheus-adapter

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: prometheus-adapter
    namespace: monitoring
  spec:
    replicas: 1

resources:
  - apiService.yaml
  - clusterRole.yaml
  - clusterRoleAggregatedMetricsReader.yaml
  - clusterRoleBindingHpaController.yaml
  - clusterRoleBinding.yaml
  - clusterRoleBindingDelegator.yaml
  - clusterRoleServerResources.yaml
  - configMap.yaml
  - deployment.yaml
  - roleBindingAuthReader.yaml
  - service.yaml
  - serviceAccount.yaml
  - serviceMonitor.yaml
