# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

images:
  - name: registry.k8s.io/prometheus-adapter/prometheus-adapter
    newName: registry.sighup.io/fury/prometheus-adapter/prometheus-adapter

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: prometheus-adapter
    namespace: monitoring
  spec:
    replicas: 1
    template:
      spec:
        containers:
          - name: prometheus-adapter
            # we increase the memory limit because we have more rules than the default from upstream and they use slightly more memory in the adapter's container.
            resources:
              requests:
                memory: 512Mi
              limits:
                memory: 1024Mi

patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: resource-metrics-auth-reader
      namespace: monitoring
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: kube-system

resources:
  - apiService.yaml
  - clusterRole.yaml
  - clusterRoleAggregatedMetricsReader.yaml
  - clusterRoleBindingHpaController.yaml
  - clusterRoleBinding.yaml
  - clusterRoleBindingDelegator.yaml
  - clusterRoleServerResources.yaml
  - configMap.yaml
  - deployment.yaml
  - roleBindingAuthReader.yaml
  - service.yaml
  - serviceAccount.yaml
  - serviceMonitor.yaml
