# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
groups:
- name: thanos-rule
  rules:
    - alert: ThanosCompactIsDown
      annotations:
        description: ThanosCompact has disappeared. Prometheus target for the component cannot be discovered.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanoscompactisdown
        summary: Thanos component has disappeared.
      expr: |
        absent(up{job=~".*thanos-compact.*"} == 1)
      for: 5m
      labels:
        severity: critical
    - alert: ThanosQueryIsDown
      annotations:
        description: ThanosQuery has disappeared. Prometheus target for the component cannot be discovered.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosqueryisdown
        summary: Thanos component has disappeared.
      expr: |
        absent(up{job=~".*thanos-query.*"} == 1)
      for: 5m
      labels:
        severity: critical
    - alert: ThanosRuleIsDown
      annotations:
        description: ThanosRule has disappeared. Prometheus target for the component cannot be discovered.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosruleisdown
        summary: Thanos component has disappeared.
      expr: |
        absent(up{job=~".*thanos-rule.*"} == 1)
      for: 5m
      labels:
        severity: critical
    - alert: ThanosSidecarIsDown
      annotations:
        description: ThanosSidecar has disappeared. Prometheus target for the component cannot be discovered.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanossidecarisdown
        summary: Thanos component has disappeared.
      expr: |
        absent(up{job=~".*thanos-sidecar.*"} == 1)
      for: 5m
      labels:
        severity: critical
    - alert: ThanosStoreIsDown
      annotations:
        description: ThanosStore has disappeared. Prometheus target for the component cannot be discovered.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosstoreisdown
        summary: Thanos component has disappeared.
      expr: |
        absent(up{job=~".*thanos-store.*"} == 1)
      for: 5m
      labels:
        severity: critical
