{
 "title": "Gluster Nodes",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(node_boot_time{job=\"gluster-node-exporter\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "description": "This graph provides an overview for CPU usage, per node, using a calculation based on the idle metric of the CPU in a 1 minute window normalized on the number of cores on the given node.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg by(instance) (rate(node_cpu{mode=\"idle\", instance=\"$node\"}[1m]))",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "CPU Saturation (Load1, Load5, Load15)",
   "type": "graph",
   "description": "This graph provides an overview for CPU saturation, per node, using a calculation based on the load average over a 1, 5, and 15 minutes windows normalized on the number of cores on the given node.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum by (instance) (node_load1{instance=\"$node\"})) / (count by (instance) (node_cpu{instance=\"$node\", mode=\"idle\"}))",
     "legendFormat": "Saturation (1m)"
    },
    {
     "expr": "(sum by (instance) (node_load5{instance=\"$node\"})) / (count by (instance) (node_cpu{instance=\"$node\", mode=\"idle\"}))",
     "legendFormat": "Saturation (5m)"
    },
    {
     "expr": "(sum by (instance) (node_load15{instance=\"$node\"})) / (count by (instance) (node_cpu{instance=\"$node\", mode=\"idle\"}))",
     "legendFormat": "Saturation (15m)"
    }
   ]
  },
  {
   "title": "Core Utilisation",
   "type": "graph",
   "description": "This graph provides an overview for CPU usage, per node, using a calculation based on the idle metric of the CPU in a 1 minute window without normalizing on the number of cores and also displaying the number of cores available on the given node.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(count by (instance) (node_cpu{instance=\"$node\", mode=\"idle\"})) - (sum by (instance) (rate(node_cpu{mode=\"idle\", instance=\"$node\"}[1m])))",
     "legendFormat": "current"
    },
    {
     "expr": "count(node_cpu{instance=\"$node\", mode=\"idle\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "This graph provides an overview for CPU usage, per node, using a calculation based on the time the CPU spent in each mode (idle, iowait, irq, nice, softirq, steal, system, user) normalized on the number of cores.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by(mode) (rate(node_cpu{instance=\"$node\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "description": "This graph provides an overview for memory utilisation, per node, by computing free memory (free, cached and buffered) and then normalizing on the total available memory.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - sum by(instance) ((node_memory_MemFree{instance=\"$node\"} + node_memory_Cached{instance=\"$node\"} + node_memory_Buffers{instance=\"$node\"})) / sum by(instance) (node_memory_MemTotal{instance=\"$node\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Memory Saturation (Swap I/O)",
   "type": "graph",
   "description": "This graph provides an overview for memory saturation, per node, by adding page-in and page-out metrics over a 1 minute window for a given node.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "1000 * sum by(instance) ((rate(node_vmstat_pgpgin{instance=\"$node\"}[1m]) + rate(node_vmstat_pgpgout{instance=\"$node\"}[1m])))",
     "legendFormat": "Swap IO"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "This graph provides a detailed view of memory occupation by showing used memory (computed subtracting free, buffers and cached memory from total memory), buffered, cached and free memory for a given node.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(\n  (node_memory_MemTotal{instance=\"$node\"}\n  - node_memory_MemFree{instance=\"$node\"}\n  - node_memory_Buffers{instance=\"$node\"}\n  - node_memory_Cached{instance=\"$node\"})\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "max(node_memory_Buffers{instance=\"$node\"})",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "max(node_memory_Cached{instance=\"$node\"})",
     "legendFormat": "memory cached"
    },
    {
     "expr": "max(node_memory_MemFree{instance=\"$node\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Disk IO Utilisation",
   "type": "graph",
   "description": "This graph provides an overview for I/O utilisation, per node, by using the node_disk_io_time_ms metric on physical devices over a 1 minute window for a given node.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by(instance) (irate(node_disk_io_time_ms{device=~\"(sd|xvd|nvme).+\", instance=\"$node\"}[1m]) / 1000)",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "graph",
   "description": "This graph provides an overview for I/O saturation, per node, by using the node_disk_io_time_weighted (that provides a measure of both I/O completion time and the backlog that may be accumulating) over a 1 minute window for a given node.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by(instance) (irate(node_disk_io_time_weighted{device=~\"(sd|xvd|nvme).+\", instance=\"$node\"}[1m]) / 1000)",
     "legendFormat": "Saturation"
    }
   ]
  },
  { "title": "Net", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Net Utilisation (Transmitted)",
   "type": "graph",
   "description": "This graph provides an overview for network utilisation, per node, by adding the rate of bytes sent/received over a 1 minute window for a given node.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) ((irate(node_network_receive_bytes{instance=\"$node\", device=~\"eth[[:digit:]]+|en.*\"}[1m]) + irate(node_network_transmit_bytes{instance=\"$node\", device=~\"eth[[:digit:]]+|en.*\"}[1m])))",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Net Saturation (Dropped)",
   "type": "graph",
   "description": "This graph provides an overview for network saturation, per node, by adding the rate of dropped packets on the receive/transmit side over a 1 minute window for a given node.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) ((irate(node_network_receive_drop{instance=\"$node\", device=~\"eth[[:digit:]]+|en.*\"}[1m]) + irate(node_network_transmit_drop{instance=\"$node\", device=~\"eth[[:digit:]]+|en.*\"}[1m])))",
     "legendFormat": "Saturation"
    }
   ]
  }
 ]
}