{
 "title": "Gluster Utilisation",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(heketi_nodes_count, cluster)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(heketi_device_count, hostname)"
   },
   {
    "name": "device",
    "label": "device",
    "query": "label_values(heketi_device_size, device)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes count",
   "type": "singlestat",
   "description": "This panel gives the number of nodes currently joined in the GlusterFS cluster.",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "heketi_nodes_count{cluster=\"$cluster\"}"
    }
   ]
  },
  { "title": "Gluster Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Gluster Cluster Utilisation",
   "type": "graph",
   "description": "This graph gives an overview of the utilisation at the cluster level.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (cluster) (heketi_device_used{cluster=\"$cluster\"} / heketi_device_size{cluster=\"$cluster\"})",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Gluster Cluster Usage",
   "type": "graph",
   "description": "This graph gives an overview of usage and max capacity at the cluster level.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) (heketi_device_used{cluster=\"$cluster\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum by (cluster) (heketi_device_size{cluster=\"$cluster\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Gluster Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Gluster Nodes Utilisation",
   "type": "graph",
   "description": "This graph gives an overview of the utilisation at single node level.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (device) (heketi_device_used{cluster=\"$cluster\", hostname=\"$node\"} / heketi_device_size{cluster=\"$cluster\", hostname=\"$node\"})",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Gluster Node Usage",
   "type": "graph",
   "description": "This graph gives an overview of usage and max capacity at single node level.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (hostname) (heketi_device_used{cluster=\"$cluster\", hostname=\"$node\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum by (hostname) (heketi_device_size{cluster=\"$cluster\", hostname=\"$node\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Gluster Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Gluster Device Utilisation",
   "type": "graph",
   "description": "This graph gives an overview of the utilisation at single device level.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "heketi_device_used{cluster=\"$cluster\", hostname=\"$node\", device=\"$device\"} / heketi_device_size{cluster=\"$cluster\", hostname = \"$node\", device = \"$device\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Gluster Device Usage",
   "type": "graph",
   "description": "This graph gives an overview of usage and max capacity at single device level.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "heketi_device_used{cluster=\"$cluster\", hostname=\"$node\", device=\"$device\"}",
     "legendFormat": "used"
    },
    {
     "expr": "heketi_device_size{cluster=\"$cluster\", hostname=\"$node\", device=\"$device\"}",
     "legendFormat": "max"
    }
   ]
  }
 ]
}