# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: v1
data:
  config.yaml: |-
    # Configuration options can be found at https://github.com/prymitive/karma/blob/main/docs/CONFIGURATION.md
    alertmanager:
      interval: 1m
      servers: []
    history:
      enabled: false
kind: ConfigMap
metadata:
  labels:
    app: karma
  name: karma-config
  namespace: monitoring
