# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: dashboard-sidecar
          image: kiwigrid/k8s-sidecar
          env:
            - name: LABEL
              value: "grafana-sighup-dashboard"
            - name: FOLDER
              value: /tmp/dashboards
            - name: RESOURCE
              # configmap and secret
              value: both
            - name: NAMESPACE
              value: "ALL"
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          volumeMounts:
            - name: grafana-shared-dashboards
              mountPath: /tmp/dashboards
        - name: datasource-sidecar
          image: kiwigrid/k8s-sidecar
          env:
            - name: LABEL
              value: "grafana-sighup-datasource"
            - name: FOLDER
              value: /tmp/datasource
            - name: RESOURCE
              # configmap and secret
              value: both
            - name: NAMESPACE
              value: "ALL"
            - name: REQ_URL
              value: http://localhost:3000/api/admin/provisioning/datasources/reload
            - name: REQ_METHOD
              value: POST
              # dummy username and password, required by reload API
            - name: REQ_USERNAME
              value: admin
            - name: REQ_PASSWORD
              value: admin
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          volumeMounts:
            - name: grafana-shared-datasources
              mountPath: /tmp/datasource
        - image: grafana/grafana
          name: grafana
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_DISABLE_LOGIN_FORM
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
          ports:
            - containerPort: 3000
              name: http
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: grafana-shared-dashboards
              mountPath: /grafana-dashboard-definitions/0
            - mountPath: /var/lib/grafana
              name: grafana-storage
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-shared-datasources
            - mountPath: /etc/grafana/provisioning/dashboards
              name: grafana-dashboards
            - mountPath: /etc/grafana
              name: grafana-config
              readOnly: false
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
      serviceAccountName: grafana
      volumes:
        - name: grafana-shared-dashboards
          emptyDir: {}
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-shared-datasources
          emptyDir: {}
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards
        - name: grafana-config
          secret:
            secretName: grafana-config
