---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: grafana
  name: grafana
spec:
  endpoints:
    - interval: 30s
      port: http
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: grafana
