- targets:
  - prometheus-k8s-0.prometheus-operated.monitoring:10901
  - prometheus-k8s-1.prometheus-operated.monitoring:10901
  - prometheus-k8s-2.prometheus-operated.monitoring:10901
  - thanos-store.monitoring:10901