# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

images:
  - name: quay.io/prometheus/blackbox-exporter
    newName: registry.sighup.io/fury/prometheus/blackbox-exporter
    newTag: v0.23.0
  - name: jimmidyson/configmap-reload
    newName: registry.sighup.io/fury/jimmidyson/configmap-reload
    newTag: v0.5.0
  - name: quay.io/brancz/kube-rbac-proxy
    newName: registry.sighup.io/fury/brancz/kube-rbac-proxy
    newTag: v0.14.0

resources:
  - clusterRole.yaml
  - clusterRoleBinding.yaml
  - configuration.yaml
  - deployment.yaml
  - prometheusRule.yml
  - service.yaml
  - serviceAccount.yaml
  - serviceMonitor.yaml
