{
 "title": "CoreDNS",
 "description": "A dashboard for the CoreDNS DNS server.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(up{job=\"kube-dns\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests Volume",
   "type": "singlestat",
   "description": "This panel gives an overview of the total requests volume over a 2 minutes time window.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{job=\"kube-dns\",instance=~\"$instance\"}[2m]))"
    }
   ]
  },
  {
   "title": "Total Responses Volume",
   "type": "singlestat",
   "description": "This panel gives an overview of the total responses volume over a 2 minutes time window.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{job=\"kube-dns\",instance=~\"$instance\"}[2m]))"
    }
   ]
  },
  {
   "title": "Total Traffic",
   "type": "singlestat",
   "description": "This panel gives an overview about the total traffic done by a given CoreDNS instance by summing up the rate of requests/responses size over a 2 minutes time windows.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(coredns_dns_request_size_bytes_sum{job=\"kube-dns\",instance=~\"$instance\"}[2m])) + sum(irate(coredns_dns_response_size_bytes_sum{job=\"kube-dns\",instance=~\"$instance\"}[2m]))"
    }
   ]
  },
  {
   "title": "Panic Count",
   "type": "singlestat",
   "description": "This panel gives an overview about the total number of CoreDNS panics.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(coredns_panics_total{job=\"kube-dns\",instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Requests Volume",
   "type": "graph",
   "description": "This graph gives an overview  on  the requests volume on a given pod receiving DNS requests on a 2 minutes time window.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,pod,proto) (irate(coredns_dns_requests_total{job=\"kube-dns\",instance=~\"$instance\"}[2m]))",
     "legendFormat": "{{ pod }}/{{ proto }}"
    }
   ]
  },
  {
   "title": "Requests by Zone",
   "type": "graph",
   "description": "This graph gives an overview  on  the requests volume subdivided by zone on a given pod receiving DNS requests on a 2 minutes time window.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,pod,zone) (irate(coredns_dns_requests_total{job=\"kube-dns\",instance=~\"$instance\"}[2m]))",
     "legendFormat": "{{ pod }}/{{ zone }}"
    }
   ]
  },
  {
   "title": "Requests by Qtype",
   "type": "graph",
   "description": "This graph gives an overview  on  the requests volume subdivided by query type on a given pod receiving DNS requests on a 2 minutes time window.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,pod,type) (irate(coredns_dns_requests_total{job=\"kube-dns\",instance=~\"$instance\"}[2m]))",
     "legendFormat": "{{ pod }}/{{ type }}"
    }
   ]
  },
  {
   "title": "Requests 99th Percentile Requests Duration",
   "type": "graph",
   "description": "This graph gives an overview of the 99th percentile requests latency for a given pod serving DNS requests.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,instance,pod) (rate(coredns_dns_request_duration_seconds_bucket{job=\"kube-dns\",instance=~\"$instance\"}[2m])))",
     "legendFormat": "{{ pod }} p99"
    }
   ]
  },
  {
   "title": "Health Requests 99th Percentile Requests Duration",
   "type": "graph",
   "description": "This graph gives an overview of the 99th percentile requests latency for a given pod serving DNS health requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,instance,pod) (rate(coredns_health_request_duration_seconds_bucket{job=\"kube-dns\",instance=~\"$instance\"}[2m])))",
     "legendFormat": "{{ pod }} p99"
    }
   ]
  },
  {
   "title": "Forward Requests Volume",
   "type": "graph",
   "description": "This graph gives an overview  on  the forward requests volume on a given pod receiving DNS requests on a 2 minutes time window.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,pod,proto) (irate(coredns_forward_requests_total{job=\"kube-dns\",instance=~\"$instance\"}[2m]))",
     "legendFormat": "{{ pod }}/{{ proto }}"
    }
   ]
  },
  {
   "title": "Forward Requests 99th Percentile Requests Duration",
   "type": "graph",
   "description": "This graph gives an overview of the 99th percentile requests latency for a given pod forwarding DNS requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,instance,pod,proto) (rate(coredns_forward_request_duration_seconds_bucket{job=\"kube-dns\",instance=~\"$instance\"}[2m])))",
     "legendFormat": "{{ pod }}/{{ proto }} p99"
    }
   ]
  },
  {
   "title": "Requests Traffic",
   "type": "graph",
   "description": "This graph gives an overview of the requests traffic for a given pod receiving DNS requests by calculating the rate of requests size over a 2 minutes window.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,pod,proto) (irate(coredns_dns_request_size_bytes_sum{job=\"kube-dns\",instance=~\"$instance\"}[2m]))",
     "legendFormat": "{{ pod }}/{{ proto }}"
    }
   ]
  },
  {
   "title": "Requests 99th Percentile Size",
   "type": "graph",
   "description": "This graph gives an overview of the 99th percentile requests size for a given pod receiving DNS requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (instance,le,pod,proto) (rate(coredns_dns_request_size_bytes_bucket{job=\"kube-dns\",instance=~\"$instance\"}[2m]))) ",
     "legendFormat": "{{ pod }}/{{proto}} p99"
    }
   ]
  },
  { "title": "Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Responses Volume",
   "type": "graph",
   "description": "This graph gives an overview  on  the responses volume on a given pod serving DNS responses on a 2 minutes time window.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,pod) (irate(coredns_dns_responses_total{job=\"kube-dns\",instance=~\"$instance\"}[2m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Responses by Rcode",
   "type": "graph",
   "description": "This graph gives an overview  on  the responses volume subdivided by response code on a given pod serving DNS responses on a 2 minutes time window.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,pod,rcode) (irate(coredns_dns_responses_total{job=\"kube-dns\",instance=~\"$instance\"}[2m]))",
     "legendFormat": "{{ pod }}/{{ rcode }}"
    }
   ]
  },
  {
   "title": "Responses Traffic",
   "type": "graph",
   "description": "This graph gives an overview of the responses traffic for a given pod serving DNS responses by calculating the rate of responses size over a 2 minutes window.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,pod,proto) (irate(coredns_dns_response_size_bytes_sum{job=\"kube-dns\",instance=~\"$instance\"}[2m]))",
     "legendFormat": "{{ pod }}/{{ proto }}"
    }
   ]
  },
  {
   "title": "Responses 99th Percentile Size",
   "type": "graph",
   "description": "This graph gives an overview of the 99th percentile responses size for a given pod serving DNS responses.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (instance,le,pod,proto) (rate(coredns_dns_response_size_bytes_bucket{job=\"kube-dns\",instance=~\"$instance\"}[2m]))) ",
     "legendFormat": "{{ pod }}/{{proto}} p99"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Cache Hitrate",
   "type": "graph",
   "description": "This graph gives an overview about DNS cache hitrate by calculating the rate of hits/misses  over a 2 minutes time window.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,pod,type) (irate(coredns_cache_hits_total{job=\"kube-dns\",instance=~\"$instance\"}[2m]))",
     "legendFormat": "{{ pod }}/{{ type }}"
    },
    {
     "expr": "sum by (instance,pod) (irate(coredns_cache_misses_total{job=\"kube-dns\",instance=~\"$instance\"}[2m]))",
     "legendFormat": "{{ pod }}/misses"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "graph",
   "description": "This graph gives an overview about DNS cache size subdivided by acknowledge/denial of existence of given pod serving DNS responses.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,pod,type) (coredns_cache_entries{job=\"kube-dns\",instance=~\"$instance\"})",
     "legendFormat": "{{ pod }}/{{ type }}"
    }
   ]
  }
 ]
}