{
 "title": "Kubernetes Cluster",
 "time": { "from": "now/w", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "description": "This graph provides an overview for CPU usage, per node, using a calculation based on the idle metric of the CPU in a 1 minute window scaled on the number of cores on the given node and normalized on the total number of cores in the cluster.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_utilisation:avg1m * node:node_num_cpu:sum / scalar(sum(node:node_num_cpu:sum))",
     "legendFormat": "{{node}}",
     "legendLink": "/d/4ac4f123aae0ff6dbaf4f4f66120033b/k8s-node-rsrc-use"
    }
   ]
  },
  {
   "title": "CPU Saturation (Load15)",
   "type": "graph",
   "description": "This graph provides an overview for CPU saturation, per node, using a calculation based on the load average over a 15 minute window scaled on the number of cores on the given node and normalized on the total number of cores in the cluster.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum  by(node) (node_load15{job=\"node-exporter\"} * on(namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:) / node:node_num_cpu:sum) / scalar(sum(min(kube_pod_info) by (node)))",
     "legendFormat": "{{node}}",
     "legendLink": "/d/4ac4f123aae0ff6dbaf4f4f66120033b/k8s-node-rsrc-use"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "description": "This graph provides an overview for memory usage, per node, by subtracting available memory form total memory and normalizing on the total memory in the cluster.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_utilisation:ratio",
     "legendFormat": "{{node}}",
     "legendLink": "/d/4ac4f123aae0ff6dbaf4f4f66120033b/k8s-node-rsrc-use"
    }
   ]
  },
  {
   "title": "Memory Saturation (Swap I/O)",
   "type": "graph",
   "description": "This graph provides an overview for memory saturation, per node, by adding page-in and page-out metrics over a 1 minute window.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_swap_io_bytes:sum_rate",
     "legendFormat": "{{node}}",
     "legendLink": "/d/4ac4f123aae0ff6dbaf4f4f66120033b/k8s-node-rsrc-use"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Disk IO Utilisation",
   "type": "graph",
   "description": "This graph provides an overview for I/O utilisation, per node, by using the node_disk_io_time_ms metric on physical devices over a 1 minute window and then normalizing on the total number of nodes in the cluster.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_disk_utilisation:avg_irate / scalar(:kube_pod_info_node_count:)",
     "legendFormat": "{{node}}",
     "legendLink": "/d/4ac4f123aae0ff6dbaf4f4f66120033b/k8s-node-rsrc-use"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "graph",
   "description": "This graph provides an overview for I/O saturation, per node, by using the node_disk_io_time_weighted (that provide a measure of both I/O completion time and the backlog that may be accumulating) over a 1 minute window and then normalizing on the total number  of nodes in the cluster.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_disk_saturation:avg_irate / scalar(:kube_pod_info_node_count:)",
     "legendFormat": "{{node}}",
     "legendLink": "/d/4ac4f123aae0ff6dbaf4f4f66120033b/k8s-node-rsrc-use"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Net Utilisation (Transmitted)",
   "type": "graph",
   "description": "This graph provides an overview for network utilisation, per node, by adding the rate of bytes sent/received by each node over a 1 minute window.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_net_utilisation:sum_irate",
     "legendFormat": "{{node}}",
     "legendLink": "/d/4ac4f123aae0ff6dbaf4f4f66120033b/k8s-node-rsrc-use"
    }
   ]
  },
  {
   "title": "Net Saturation (Dropped)",
   "type": "graph",
   "description": "This graph provides an overview for network saturation, per node, by adding the rate of dropped packets by each node on the receive/transmit side over a 1 minute window.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_net_saturation:sum_irate",
     "legendFormat": "{{node}}",
     "legendLink": "/d/4ac4f123aae0ff6dbaf4f4f66120033b/k8s-node-rsrc-use"
    }
   ]
  },
  {
   "title": "Weave-net unreachable IP percentage",
   "type": "graph",
   "description": "This graph gives an overview about the percentage of IP address owned by unreachable Weave-net peers.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "weave_ipam_unreachable_percentage{job=\"weave-net\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Weave-net connections",
   "type": "graph",
   "description": "This graph gives an overview of the connection status of Weave-net peers.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (rate(weave_connections[1m]))",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Disk Capacity",
   "type": "graph",
   "description": "This graph provides an overview for disk capacity, per node, by subtracting from the filesystem size the bytes still available and the normalizing on the filesystem size.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(max(node_filesystem_size{fstype=~\"ext[234]|btrfs|xfs|zfs\"} - node_filesystem_avail{fstype=~\"ext[234]|btrfs|xfs|zfs\"}) by (device,pod,namespace)) by (pod,namespace)\n/ scalar(sum(max(node_filesystem_size{fstype=~\"ext[234]|btrfs|xfs|zfs\"}) by (device,pod,namespace)))\n* on (namespace, pod) group_left (node) node_namespace_pod:kube_pod_info:\n",
     "legendFormat": "{{node}}",
     "legendLink": "/d/4ac4f123aae0ff6dbaf4f4f66120033b/k8s-node-rsrc-use"
    }
   ]
  }
 ]
}