{
 "title": "Kubernetes Deployments",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "deployment_namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_metadata_generation, namespace)"
   },
   {
    "name": "deployment_name",
    "label": "Deployment",
    "query": "label_values(kube_deployment_metadata_generation{namespace=\"$deployment_namespace\"}, deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "singlestat",
   "description": "This panel provides an overview for CPU usage, per deployment, by summing up the CPU time used by all the pods in the given deployment over a 3 minutes window.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$deployment_namespace\",pod_name=~\"$deployment_name.*\",container_name!=\"POD\",container_name!=\"\"}[3m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "description": "This panel provides an overview for memory usage, per deployment, by summing up the memory used by all the pods in the given deployment.",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$deployment_namespace\",pod_name=~\"$deployment_name.*\",container_name!=\"POD\",container_name!=\"\"})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "description": "This panel provides an overview for network usage, per deployment, by summing up bytes received/transmitted by all the pods in the given deployment over a 3 minutes window.",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$deployment_namespace\",pod_name=~\"$deployment_name.*\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"$deployment_namespace\",pod_name=~\"$deployment_name.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "description": "This query provides the desired replicas number for the given deployment.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "singlestat",
   "description": "This panel provides the currently available replicas number for the given deployment.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "singlestat",
   "description": "This panel provides the observed generation (the deployment revision that pods are running) for the given deployment.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_deployment_status_observed_generation{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "singlestat",
   "description": "This panel provides the observed generation (the deployment revision that pods are running) for the given deployment.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_deployment_metadata_generation{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  { "title": "Replicas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Replicas",
   "type": "graph",
   "description": "This graph provides an overview of the replica number status of a deployment over a given time window.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "This graph provides the CPU usage calculated on a 1 minute time window of all the pods of a given deployment.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,pod) (label_replace(rate(container_cpu_usage_seconds_total{job=\"kubelet\",container_name!=\"POD\",container_name!=\"\"}[1m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\") * on (namespace,pod) group_left(created_by_name) (kube_pod_info{created_by_name=~\"$deployment_name.*\",namespace=\"$deployment_namespace\"}))",
     "legendFormat": "$deployment_name/{{ pod }}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "This graph provides the memory usage of all the pods of a given deployment.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,pod) (label_replace(container_memory_usage_bytes{job=\"kubelet\",container_name!=\"POD\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\") * on (namespace,pod) group_left(created_by_name) (kube_pod_info{created_by_name=~\"$deployment_name.*\",namespace=\"$deployment_namespace\"}))",
     "legendFormat": "$deployment_name/{{ pod }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Network Usage",
   "type": "graph",
   "description": "This graph provides the network usage by adding bytes received/sent over a 1 minute window by each each pod in a given deployment.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,pod) (label_replace(rate(container_network_transmit_bytes_total{job=\"kubelet\"}[1m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\") * on (namespace,pod) group_left(created_by_name) (kube_pod_info{created_by_name=~\"$deployment_name.*\",namespace=\"$deployment_namespace\"}))\n + \nsum by (namespace,pod) (label_replace(rate(container_network_receive_bytes_total{job=\"kubelet\"}[1m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\") * on (namespace,pod) group_left(created_by_name) (kube_pod_info{created_by_name=~\"$deployment_name.*\",namespace=\"$deployment_namespace\"}))",
     "legendFormat": "$deployment_name/{{ pod }}"
    }
   ]
  }
 ]
}