# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - ../prometheus-operator
  - ../prometheus-operated
  - datasources
  - deploy.yaml

configMapGenerator:
  - name: mimir-distributed-config
    namespace: monitoring
    files:
      - config/mimir.yaml

patchesStrategicMerge:
  - |-
    apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    metadata:
      name: k8s
      namespace: monitoring
    spec:
      remoteWrite:
        - url: http://mimir-distributed-gateway/api/v1/push