{
 "title": "Kubernetes Pods",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\",pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "This graph provides the CPU usage and the CPU limits (if any) of the containers belonging to a given pod.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{job=\"kubelet\",container!=\"POD\",container!=\"\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\"}[1m])",
     "legendFormat": "{{ pod }}/{{ container }} current"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{job=\"kube-state-metrics\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\"}",
     "legendFormat": "{{ pod }}/{{ container}} limit"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "This graph provides the memory usage and the memory limits (if any) of the containers belonging to a given pod.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{job=\"kubelet\",container!=\"POD\",container!=\"\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\"}",
     "legendFormat": "{{ pod }}/{{ container }} current"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{job=\"kube-state-metrics\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\"}",
     "legendFormat": "{{ pod }}/{{ container }} limit"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Network I/O",
   "type": "graph",
   "description": "This graph provides the network usage of all the containers belonging to a given pod. It's not possible to have the network usage per-container because all the containers in a given pod share the same network.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,pod) (rate(container_network_transmit_bytes_total{job=\"kubelet\",namespace=\"$namespace\",pod=\"$pod\"}[1m]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "-(sum by (namespace,pod) (rate(container_network_receive_bytes_total{job=\"kubelet\",namespace=\"$namespace\",pod=\"$pod\"}[1m])))",
     "legendFormat": "Received"
    }
   ]
  }
 ]
}