{
 "title": "Kubernetes Nodes",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(kube_node_info, node)"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "description": "This graph provides an overview for CPU usage, per node, using a calculation based on the idle metric of the CPU in a 1 minute window normalized on the number of cores on the given node.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_utilisation:avg1m{node=\"$node\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "CPU Saturation (Load1, Load5, Load15)",
   "type": "graph",
   "description": "This graph provides an overview for CPU saturation, per node, using a calculation based on the load average over a 1, 5, and 15 minutes windows normalized on the number of cores on the given node.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_saturation_load1:{node=\"$node\"}",
     "legendFormat": "Saturation (1m)"
    },
    {
     "expr": "sum\n  by(node) (node_load5{job=\"node-exporter\"} * on(namespace, pod) group_left(node)\n  node_namespace_pod:kube_pod_info:{node=\"$node\"}) / node:node_num_cpu:sum{node=\"$node\"}",
     "legendFormat": "Saturation (5m)"
    },
    {
     "expr": "sum\n  by(node) (node_load15{job=\"node-exporter\"} * on(namespace, pod) group_left(node)\n  node_namespace_pod:kube_pod_info:{node=\"$node\"}) / node:node_num_cpu:sum{node=\"$node\"}",
     "legendFormat": "Saturation (15m)"
    }
   ]
  },
  {
   "title": "Core Utilisation",
   "type": "graph",
   "description": "This graph provides an overview for CPU usage, per node, using a calculation based on the idle metric of the CPU in a 1 minute window without normalizing on the number of cores and also displaying the number of cores available on the given node.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node:node_num_cpu:sum{node=\"$node\"} - (sum by (node) (rate(node_cpu{job=\"node-exporter\", mode=\"idle\"}[1m]) * on(namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=\"$node\"}))",
     "legendFormat": "current"
    },
    {
     "expr": "node:node_num_cpu:sum{node=\"$node\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "This graph provides an overview for CPU usage, per node, using a calculation based on the time the CPU spent in each mode (idle, iowait, irq, nice, softirq, steal, system, user) normalized on the number of cores.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by(mode) (rate(node_cpu{job=\"node-exporter\"}[1m]) * on(namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=\"$node\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Pod",
   "type": "graph",
   "description": "This graph provides an overview for CPU usage, per node, using a calculation based on the millicore used by each pod in a 1 minute window.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,pod_name) (rate(container_cpu_usage_seconds_total{job=\"kubelet\", container_name!=\"POD\", container_name!=\"\"}[1m]) * on(namespace, pod_name) group_left(node) label_replace(node_namespace_pod:kube_pod_info:{node=\"$node\"}, \"pod_name\", \"$1\", \"pod\", \"(.*)\"))",
     "legendFormat": "{{ namespace }}/{{ pod_name }}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "description": "This graph provides an overview for memory utilisation, per node, by computing free memory (free, cached and buffered) and then normalizing on the total available memory.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_utilisation:{node=\"$node\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Memory Saturation (Swap I/O)",
   "type": "graph",
   "description": "This graph provides an overview for memory saturation, per node, by adding page-in and page-out metrics over a 1 minute window for a given node.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_swap_io_bytes:sum_rate{node=\"$node\"}",
     "legendFormat": "Swap IO"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "This graph provides a detailed view of memory occupation by showing used memory (computed subtracting free, buffers and cached memory from total memory), buffered, cached and free memory for a given node.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(\n  (node_memory_MemTotal{job=\"node-exporter\"}\n  - node_memory_MemFree{job=\"node-exporter\"}\n  - node_memory_Buffers{job=\"node-exporter\"}\n  - node_memory_Cached{job=\"node-exporter\"}) *\n  on(namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=\"$node\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "max(node_memory_Buffers{job=\"node-exporter\"} * on(namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=\"$node\"})",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "max(node_memory_Cached{job=\"node-exporter\"} * on(namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=\"$node\"})",
     "legendFormat": "memory cached"
    },
    {
     "expr": "max(node_memory_MemFree{job=\"node-exporter\"} * on(namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=\"$node\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "graph",
   "description": "This graph provides an overview for memory usage, per node, using a calculation based on the memory used by each pod scheduled on the given node.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,pod_name) (container_memory_usage_bytes{job=\"kubelet\", container_name!=\"POD\", container_name!=\"\"} * on(namespace, pod_name) group_left(node) label_replace(node_namespace_pod:kube_pod_info:{node=\"$node\"}, \"pod_name\", \"$1\", \"pod\", \"(.*)\"))",
     "legendFormat": "{{ namespace }}/{{ pod_name }}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Disk IO Utilisation",
   "type": "graph",
   "description": "This graph provides an overview for I/O utilisation, per node, by using the node_disk_io_time_ms metric on physical devices over a 1 minute window for a given node.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_disk_utilisation:avg_irate{node=\"$node\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "graph",
   "description": "This graph provides an overview for I/O saturation, per node, by using the node_disk_io_time_weighted (that provides a measure of both I/O completion time and the backlog that may be accumulating) over a 1 minute window for a given node.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_disk_saturation:avg_irate{node=\"$node\"}",
     "legendFormat": "Saturation"
    }
   ]
  },
  {
   "title": "Disk Utilisation",
   "type": "graph",
   "description": "This graph provides an overview for disk capacity, per node, by subtracting from the filesystem size the bytes still available and the normalizing on the filesystem size for a given node.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_filesystem_usage:\n* on (namespace, pod) group_left (node) node_namespace_pod:kube_pod_info:{node=\"$node\"}\n",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "description": "This graph provides an overview for disk usage, per node, by subtracting from the filesystem size the bytes still available also displaying the total size of the filesystem for a given node.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(max by (namespace, pod, device)\n(node_filesystem_size_bytes{job=\"node-exporter\", fstype=~\"ext[234]|btrfs|xfs|zfs|vfat|tmpfs\"}) *\non (namespace, pod) group_left (node) node_namespace_pod:kube_pod_info:{node=\"$node\"}) \n- \n(max by (namespace, pod, service)\n(node_filesystem_avail_bytes{job=\"node-exporter\", fstype=~\"ext[234]|btrfs|xfs|zfs|vfat|tmpfs\"}) *\non (namespace, pod) group_left (node) node_namespace_pod:kube_pod_info:{node=\"$node\"})",
     "legendFormat": "{{ device }} used"
    },
    {
     "expr": "max by (namespace, pod, device)\n(node_filesystem_size_bytes{job=\"node-exporter\", fstype=~\"ext[234]|btrfs|xfs|zfs|vfat|tmpfs\"}) *\non (namespace, pod) group_left (node) node_namespace_pod:kube_pod_info:{node=\"$node\"}",
     "legendFormat": "{{ device }} total"
    }
   ]
  },
  {
   "title": "Inode Utilisation",
   "type": "graph",
   "description": "This graph provides an overview for inodes capacity per node, by dividing free inodes  by total inodes for all filesystems in a given node.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": " max by (device, namespace, pod) (1 - (node_filesystem_files_free{fstype=~\"ext[234]|btrfs|xfs|zfs\"} / node_filesystem_files{fstype=~\"ext[234]|btrfs|xfs|zfs\"})) * on (namespace, pod) group_left (node) node_namespace_pod:kube_pod_info:{node=\"$node\"}",
     "legendFormat": "{{device}} "
    }
   ]
  },
  {
   "title": "Inode Usage",
   "type": "graph",
   "description": "This graph provides an overview for inodes usage, per node, by subtracting from the total inodes count  the free inodes count and also displaying the total inodes count of the filesystem for a given node.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(max by (namespace, pod, device)\n(node_filesystem_files{job=\"node-exporter\", fstype=~\"ext[234]|btrfs|xfs|zfs\"}) *\non (namespace, pod) group_left (node) node_namespace_pod:kube_pod_info:{node=\"$node\"}) \n- \n(max by (namespace, pod, device)\n(node_filesystem_files_free{job=\"node-exporter\", fstype=~\"ext[234]|btrfs|xfs|zfs\"}) *\non (namespace, pod) group_left (node) node_namespace_pod:kube_pod_info:{node=\"$node\"})",
     "legendFormat": "used"
    },
    {
     "expr": "max by (namespace, pod, device)\n(node_filesystem_files{job=\"node-exporter\", fstype=~\"ext[234]|btrfs|xfs|zfs\"}) *\non (namespace, pod) group_left (node) node_namespace_pod:kube_pod_info:{node=\"$node\"}",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Net", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Net Utilisation (Transmitted)",
   "type": "graph",
   "description": "This graph provides an overview for network utilisation, per node, by adding the rate of bytes sent/received over a 1 minute window for a given node.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_net_utilisation:sum_irate{node=\"$node\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Net Saturation (Dropped)",
   "type": "graph",
   "description": "This graph provides an overview for network saturation, per node, by adding the rate of dropped packets on the receive/transmit side over a 1 minute window for a given node.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_net_saturation:sum_irate{node=\"$node\"}",
     "legendFormat": "Saturation"
    }
   ]
  }
 ]
}