{
 "title": "Kubernetes StatefulSets",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_statefulset_metadata_generation{job=\"kube-state-metrics\"}, namespace)"
   },
   {
    "name": "statefulset",
    "label": "Name",
    "query": "label_values(kube_statefulset_metadata_generation{job=\"kube-state-metrics\", namespace=\"$namespace\"}, statefulset)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "singlestat",
   "description": "This panel provides an overview for CPU usage, per StatefulSet, by summing up the CPU time used by all the pods in the given StatefulSet over a 3 minutes window.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$statefulset.*\", container!=\"POD\", container!=\"\"}[3m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "description": "This panel provides an overview for CPU usage, per StatefulSet, by summing up the CPU time used by all the pods in the given StatefulSet over a 3 minutes window.",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$statefulset.*\", container!=\"POD\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "description": "This panel provides an overview for network usage, per StatefulSet, by summing up bytes received/transmitted by all the pods in the given StatefulSet over a 3 minutes window.",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$statefulset.*\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$statefulset.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "description": "This panel provides the desired replicas number for the given StatefulSets.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{job=\"kube-state-metrics\", namespace=\"$namespace\", statefulset=\"$statefulset\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Replicas of current version",
   "type": "singlestat",
   "description": "This panel provides the currently available replicas number for the given StatefulSets.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(kube_statefulset_status_replicas_current{job=\"kube-state-metrics\", namespace=\"$namespace\", statefulset=\"$statefulset\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "singlestat",
   "description": "This panel provides the observed generation (the StatefulSet revision that pods are running) for the given StatefulSet.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_statefulset_status_observed_generation{job=\"kube-state-metrics\",  namespace=\"$namespace\", statefulset=\"$statefulset\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "singlestat",
   "description": "This panel provides the metadata generation (the StatefulSet revision that we want to deploy) for the given StatefulSet.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_statefulset_metadata_generation{job=\"kube-state-metrics\", statefulset=\"$statefulset\", namespace=\"$namespace\"}) without (instance, pod)"
    }
   ]
  },
  { "title": "Replicas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Replicas",
   "type": "graph",
   "description": "This graph provides an overview of the replica number status of a StatefulSet over a given time window.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{job=\"kube-state-metrics\", statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "replicas specified"
    },
    {
     "expr": "max(kube_statefulset_status_replicas{job=\"kube-state-metrics\", statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "replicas created"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_ready{job=\"kube-state-metrics\", statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "ready"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_current{job=\"kube-state-metrics\", statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "replicas of current version"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_updated{job=\"kube-state-metrics\", statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "updated"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "This graph provides the CPU usage calculated on a 1 minute time window of all the pods of a given StatefulSet.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,pod) (label_replace(rate(container_cpu_usage_seconds_total{job=\"kubelet\",container!=\"POD\",container!=\"\"}[1m]), \"pod\", \"$1\", \"pod\", \"(.*)\") * on (namespace,pod) group_left(created_by_name) (kube_pod_info{created_by_name=~\"$statefulset.*\",namespace=\"$namespace\"}))",
     "legendFormat": "$statefulset/{{ pod }}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "This graph provides the memory usage of all the pods of a given StatefulSet.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,pod) (label_replace(container_memory_usage_bytes{job=\"kubelet\",container!=\"POD\",container!=\"\"}, \"pod\", \"$1\", \"pod\", \"(.*)\") * on (namespace,pod) group_left(created_by_name) (kube_pod_info{created_by_name=~\"$statefulset.*\",namespace=\"$namespace\"}))",
     "legendFormat": "$statefulset/{{ pod }}"
    }
   ]
  },
  { "title": "Persistent Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Persistent Volumes Utilisation",
   "type": "graph",
   "description": "This graph provides an overview about the utilisation of the persistent volumes attached to the given statefulset.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes) * on(namespace, persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\",pod=~\"$statefulset.*\"}",
     "legendFormat": "{{ namespace }}/{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Persistence Volumes Inodes Utilisation",
   "type": "graph",
   "description": "This graph provides an overview about the inodes utilisation of the persistent volumes attached to the given statefulset.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(kubelet_volume_stats_inodes_used / kubelet_volume_stats_inodes) * on(namespace, persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\",pod=~\"$statefulset.*\"}",
     "legendFormat": "{{ namespace }}/{{ persistentvolumeclaim }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Network Usage",
   "type": "graph",
   "description": "This graph provides the network usage by adding bytes received/sent over a 1 minute window by each each pod in a given StatefulSet.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,pod) (label_replace(rate(container_network_transmit_bytes_total{job=\"kubelet\"}[1m]), \"pod\", \"$1\", \"pod\", \"(.*)\") * on (namespace,pod) group_left(created_by_name) (kube_pod_info{created_by_name=~\"$statefulset.*\",namespace=\"$namespace\"}))\n + \nsum by (namespace,pod) (label_replace(rate(container_network_receive_bytes_total{job=\"kubelet\"}[1m]), \"pod\", \"$1\", \"pod\", \"(.*)\") * on (namespace,pod) group_left(created_by_name) (kube_pod_info{created_by_name=~\"$statefulset.*\",namespace=\"$namespace\"}))",
     "legendFormat": "$statefulset/{{ pod }}"
    }
   ]
  }
 ]
}