# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-proxy-metrics
  labels:
    k8s-app: kube-proxy-metrics
    k8s-proxied-app: kube-proxy
spec:
  selector:
    matchLabels:
      k8s-app: kube-proxy-metrics
      k8s-proxied-app: kube-proxy
  template:
    metadata:
      labels:
        k8s-app: kube-proxy-metrics
        k8s-proxied-app: kube-proxy
    spec:
      tolerations:
      - operator: Exists
      serviceAccountName: kube-proxy-metrics
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
      hostNetwork: true
      containers:
      - name: kube-proxy-metrics
        image: kube-rbac-proxy
        args:
        - --logtostderr
        - --secure-listen-address=0.0.0.0:18443
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - --upstream=http://127.0.0.1:10249/
        ports:
        - containerPort: 18443
          name: https
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 190Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-proxy-metrics
    k8s-proxied-app: kube-proxy
  name: kube-proxy-metrics
spec:
  ports:
  - name: https
    port: 18443
    targetPort: https
  selector:
    k8s-app: kube-proxy-metrics
    k8s-proxied-app: kube-proxy
