# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

commonLabels:
  module.kfd.sighup.io/name: "monitoring"
  module.kfd.sighup.io/version: "v1.13.0"
  module.kfd.sighup.io/component: "kube-proxy-metrics"
  kfd.sighup.io/source: "kustomize"

images:
- name: kube-rbac-proxy
  newName: registry.sighup.io/fury/brancz/kube-rbac-proxy
  newTag: v0.11.0

resources:
  - dashboards
  - deploy.yml
  - rbac.yml
  - sm.yml
