# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: v1
kind: Service
metadata:
  name: thanos-query
  namespace: "monitoring"
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/version: 0.30.0
    app.kubernetes.io/component: query
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
      nodePort: null
  selector:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/version: 0.30.0
    app.kubernetes.io/component: query
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     name: thanos-sidecar
#   name: thanos-sidecar
# spec:
#   clusterIP: None
#   selector:
#     app: prometheus
#   ports:
#     - name: grpc
#       port: 10901
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-query-grpc
  namespace: "monitoring"
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/version: 0.30.0
    app.kubernetes.io/component: query
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 10901
      targetPort: grpc
      protocol: TCP
      name: grpc
      nodePort: null
  selector:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/version: 0.30.0
    app.kubernetes.io/component: query