# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

generatorOptions:
  labels:
    grafana-sighup-dashboard: default
  disableNameSuffixHash: true

resources:
  - ../bases/coredns
  - ../bases/default
  - rules.yml
  - service-monitors/controller-manager.yml
  - service-monitors/etcd.yml
  - service-monitors/scheduler.yml
  - services/controller-manager.yml
  - services/etcd.yml
  - services/scheduler.yml

configMapGenerator:
  - name: sighup-kubeadm-dashboard-definitions
    files:
      - dashboards/controller-manager.json
      - dashboards/scheduler.json
  - name: sighup-etcd-dashboard-definitions
    files:
      - dashboards/etcd.json
