# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

global:
  resolve_timeout: 5m
  smtp_smarthost: "example.org:465"
  smtp_from: "support@example.org"
  smtp_require_tls: false
route:
  group_by: ['alertname', 'cluster', 'service', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'sighup-team'
  routes:
  - match:
      alertname: DeadMansSwitch
    group_wait: 30s
    group_interval: 1m
    repeat_interval: 1m
    receiver: healthchecks
  - match:
    receiver: 'sighup-team'
receivers:
  - name: 'sighup-team'
    slack_configs:
      - channel: kubernetes-alerts
        api_url: 'https://hooks.slack.com/services/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA-'
        send_resolved: true
    email_configs:
      - to: 'support@example.org'
        send_resolved: true
  - name: 'healthchecks'
    webhook_configs:
      - url: 'https://hc-ping.com/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
templates:
  - '/etc/alertmanager/config/*.tmpl'