global:
  resolve_timeout: 5m

templates:
  - '/etc/alertmanager/config/*.tmpl'

route:
  group_by: [alertname]
  group_wait: 30s
  group_interval: 1s
  repeat_interval: 1h
  receiver: noreceiver

receivers:
  - name: noreceiver
