# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-query
  name: thanos-query
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: http
      name: http
    - port: 10901
      protocol: TCP
      targetPort: grpc
      name: grpc
  selector:
    app: thanos-query
  sessionAffinity: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-query
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  labels:
    app: thanos-query
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      serviceAccountName: thanos-query
      containers:
        - name: thanos-query
          image: thanos
          args:
            - query
            - --log.level=info
            - --query.replica-label=replica
            - --store.sd-files=/etc/thanos/store-sd.yaml
            - --query.timeout=5m
            - --store.response-timeout=15s
          ports:
            - name: http
              containerPort: 10902
            - name: grpc
              containerPort: 10901
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /-/healthy
              port: http
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /-/ready
              port: http
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 50m
              memory: 500Mi
            limits:
              memory: 4000Mi
          volumeMounts:
            - name: config
              mountPath: /etc/thanos
      volumes:
        - name: config
          configMap:
            name: thanos-query
