# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

generatorOptions:
  labels:
    grafana-sighup-dashboard: default
  annotations:
    grafana-folder: "Kubernetes Components"
  disableNameSuffixHash: true

resources:
  - service-monitors/coredns.yml

configMapGenerator:
  - name: sighup-coredns-dashboard-definition
    files:
      - dashboards/coredns.json
