# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - thanos-rule.yaml
  - servicemonitor.yml

images:
  - name: thanos
    newName: registry.sighup.io/fury/thanos
    newTag: v0.24.0

configMapGenerator:
  # description: application alerts handled by thanos-rule
  # used-by: Thanos Rule
  - name: alerts
    files:
      - prometheus-alerts.yaml=prometheus-alerts.yaml
  # description: Discovery config for TQ instances used to evaluate alert rules
  # used-by: Thanos Rule
  - name: thanos-rule
    files:
      - query-sd.yaml=query-sd.yaml
