---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-controller-manager
  name: kube-controller-manager
spec:
  ports:
  - name: metrics
    port: 10257
    protocol: TCP
  selector:
    component: kube-controller-manager
