# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  namespace: monitoring
  name: deadmanswitch
spec:
  route:
    matchers:
      - name: alertname
        matchType: "="
        value: DeadMansSwitch
    receiver: healthchecks
    repeatInterval: 30s
    groupWait: 1m
    groupInterval: 1m
  receivers:
    - name: healthchecks
      webhookConfigs:
        - urlSecret:
            name: healthchecks-webhook
            key: url
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  namespace: monitoring
  name: infra
spec:
  route:
    matchers:
      - name: namespace
        matchType: "=~"
        value: "calico-api|calico-system|cert-manager|gatekeeper-system|ingress-nginx|kube-system|logging|monitoring|pomerium|tigera-operator|vmware-system-csi"
      - name: alertname
        matchType: "=~"
        value: "TargetDown|KubePersistentVolumeFillingUp|NginxIngressCertificateExpiration|NginxIngressLatencyTooHigh|NginxIngressFailedReload|NginxIngressFailureRate|NginxIngressDown"
    groupBy:
      - alertname
    receiver: infra
  receivers:
    - name: infra
      slackConfigs:
        - apiURL:
            name: infra-slack-webhook
            key: url
          sendResolved: true
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  namespace: monitoring
  name: k8s
spec:
  route:
    matchers:
      - name: alertname
        matchType: "=~"
        value: "NodeNetworkInterfaceFlapping|NodeClockSkewDetected|KubeAPIDown|KubeletDown|KubeletTooManyPods|KubeNodeNotReady|KubeClientCertificateExpiration|NodeFileDescriptorLimit|NodeFilesystemAlmostOutOfFiles|NodeFilesystemAlmostOutOfSpace|NodeFilesystemFilesFillingUp|NodeFilesystemSpaceFillingUp|NodeRAIDDegraded|NodeRAIDDiskFailure|etcdInsufficientMembers|etcdMembersDown|etcdNoLeader|CoreDNSPanic|CoreDNSHealthRequestsLatency|KubeControllerManagerDown|KubeSchedulerDown|PrometheusRuleFailures|AlertmanagerClusterDown|AlertmanagerConfigInconsistent|AlertmanagerFailedReload|X509CertificateExpiration|X509CertificateRenewal"
    groupBy:
      - alertname
    receiver: k8s
  receivers:
    - name: k8s
      slackConfigs:
        - apiURL:
            name: k8s-slack-webhook
            key: url
          sendResolved: true
